# Generated by Django 6.1 on 2026-08-14 23:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True)),
                ('terminal', models.CharField(max_length=20)),
                ('is_available', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Flights',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flight_number', models.CharField(max_length=20)),
                ('destination', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('scheduled', 'scheduled'), ('boarding', 'boarding '), ('departed', 'departed'), ('delayed', 'delayed'), ('cancelled', 'cancelled')], default='scheduled', max_length=20)),
                ('departure_time', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('gate_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='flights', to='airpot.gates')),
            ],
        ),
    ]
